services:
  - type: web
    name: skincare-ai
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm run start:deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RENDER
        value: "true"
      - key: REACT_APP_BUILD_PATH
        value: "/opt/render/project/src/build"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
